config/routes.rb
Rails.application.routes.draw do

  get 'errors/not_found'
  get 'errors/internal_server_error'

  resources :access_requests

  root 'pages#home'

  devise_for :users, controllers: { sessions: "users/sessions", profiles: "users/profiles", registrations: "users/registrations"}

  get 'posts/list' => 'posts#list'
  resources :posts

  resources :comments, except: [:new]

  resources :settings

  match "/404", to: "errors#not_found", via: :all
  match "/500", to: "errors#internal_server_error", via: :all

  get 'articles/:articleid(/:transcriptionid)' => 'articles#show', as: :show_article
  get 'articles' => 'articles#index', as: :articles

  get 'biography' => 'pages#biography'
  get 'bibliography' => 'pages#bibliography'

  get "comments/new/:itemid(/:pid)" => 'comments#new', as: :new_comment
  get "comments/list/:itemid(/:pid)" => 'comments#list', as: :list_comments

  get "index/(:expressionid)" => 'indices/indices#index'

  get "index/:expressionid/names/list(/:category)" => 'indices/names#list'
  get "index/:expressionid/names/show(/:nameid)" => 'indices/names#show'
  get "index/:expressionid/names/categories" => 'indices/names#categories'

  get "index/:expressionid/titles/list(/:category)" => 'indices/titles#list'
  get "index/:expressionid/titles/show(/:titleid)" => 'indices/titles#show'
  get "index/:expressionid/titles/categories" => 'indices/titles#categories'

  get "index/:expressionid/quotes/list(/:category)" => 'indices/quotes#list'
  get "index/:expressionid/quotes/show(/:quoteid)" => 'indices/quotes#show'
  get "index/:expressionid/quotes/categories" => 'indices/quotes#categories'

scope 'codices' do
  get 'list' => 'codices#list'
  get '(/:shortid)' => 'codices#show'
end
scope 'paragraphs' do
  get 'index' => 'paragraphs#index'
  get 'info' => 'paragraphs#info'
  get 'plaintext' => 'paragraphs#plaintext'
  get 'show2' => 'paragraphs#show2'

  get 'collation/:itemid' => 'paragraphs#collation', as: :paragraphs_collation
  get 'xml/:itemid/:pid(/:msslug)' => 'paragraphs#xml', as: :paragraphs_xml
  get 'json/:itemid/(/:msslug)(/:transcriptslug)' => 'paragraphs#json', as: :paragraphs_json
  get 'variants/:itemid/(/:msslug)(/:transcriptslug)' => 'paragraphs#variants', as: :paragraphs_variants
  get 'notes/:itemid/(/:msslug)(/:transcriptslug)' => 'paragraphs#notes', as: :paragraphs_notes

  get ':itemid/:pid(/:msslug)' => 'paragraphs#show'
end

  get 'permissions' => 'pages#permissions'

  get 'search' => 'search#show', as: :show_search
  get 'search/questions' => 'search#questions', as: :search_questions
  get 'search/index' => 'search#index', as: :show_search_index
scope "text" do
  get '' => 'text#index'
  get 'draft_permissions/:itemid' => 'text#draft_permissions'
  get 'questions(/:resourceid)' => 'text#questions', as: :table_of_questions
  get 'info/:itemid' => 'text#info', :constraints => { :itemid => /[0-9A-Za-z\-\.]+/ }
  get 'status/:itemid' => 'text#status'
  get 'toc/:itemid(/:msslug)' => 'text#toc'
  get 'plaintext/:itemid(/:msslug)(/:transcriptslug)' =>'text#plain_text', as: :plain_text
  get 'clean/:itemid(/:msslug)(/:transcriptslug)' =>'text#clean', as: :clean
  get 'xml/:itemid(/:msslug)(/:transcriptslug)' => 'text#xml'
  get 'pdf' => 'text#pdf'
  get 'archive' => 'text#archive'
  get ':itemid(/:msslug)(/:transcriptslug)' => 'text#show', as: :show_text
end

  get 'paragraphimage/showfoliozoom' => 'paragraphimage#showfoliozoom'
  get 'paragraphimage/showzoom/:itemid/:msslug' => 'paragraphimage#showzoom'

  get 'users/profiles/:id' => 'users/profiles#show', as: :users_profile
  delete 'users/profiles/:id' => 'users/profiles#destroy', as: :destroy_users_profile
  put 'users/profiles/:id' => 'users/profiles#update', as: :update_users_profile
  post 'users/profiles' => 'users/profiles#create', as: :create_users_profile
  get 'users/profiles' => 'users/profiles#index'

  get 'accesspoints' => 'access_points#index', as: :access_points
  get 'accesspoints/:commentaryid/:itemid/:role' => 'access_points#show', as: :access_point
  post 'accesspoints/:id' => 'access_points#create', as: :create_access_point
  delete 'accesspoints/:id' => 'access_points#destroy', as: :delete_access_point

  match "/:resourceid", to: "text#questions", via: :all

end

app/models/text.rb
#this is a poorly named model 
#it does not exactly coorrespond to the text controller
#it probably should be renamed to something like
# 'AccessPoint'
class Text < ActiveRecord::Base
	has_and_belongs_to_many :users
end

app/controllers/text_controller.rb
class TextController < ApplicationController
	include TextMethods

	#TODO this make question list the index page
	# current division between index and question list is confusing
  def index
		if params["resourceid"]
			redirect_to "/text/questions?resourceid=#{params["resourceid"]}"
		else
			redirect_to "/text/questions"
		end
	end
	def questions
		if params[:resourceid] != nil
			#I'm using the full Id rather than short_id because not all resources in db have a short_id yet. this needs to be added
			#TODO review lbp resource find, and see if the request looking for resource using short id in query in necessary
			# an alternative would be to construct to the full from the short_id and then use one and the same query to get the resource properties
			if params[:resourceid].include?("http")
				@resource = Lbp::Resource.find(params[:resourceid])
			else
				@resource = Lbp::Resource.find("http://scta.info/resource/#{params[:resourceid]}")
			end
			# error handling
			# checks to make sure resource is not empty
			# if empty reroutes to 404 error, avoiding a method not found error below.
			if !(@resource.results.count > 0)
				raise ActionController::RoutingError.new('Not Found')
			end

			if @resource.type.short_id == "workGroup"
				@results = @resource.parts_display
				@expression_results = @resource.expressions_display
				@info = @resource.info_display
				render "text/questions/workgrouplist"
			elsif @resource.type.short_id == "expressionType"
				@results = @resource.structure_items_by_expression_display
				@info = @resource.info_display
				@expressions = @results.map {|result| {expression: result[:expression], expressiontitle: result[:expressiontitle], authorTitle: result[:authorTitle]}}.uniq!
				render "text/questions/expressionType_expressionList"
			# TODO need an lbp class for Person
			elsif @resource.type.short_id == "person"
				@results = MiscQuery.new.author_expression_list(@resource.short_id)
				@articleresults = MiscQuery.new.author_article_list(@resource.short_id)
				@article_members_results = MiscQuery.new.author_members_article_list(@resource.short_id)
				render "text/questions/authorlist"
			elsif @resource.value("http://scta.info/property/structureType").to_s.include? "structureItem"
				redirect_to "/text/#{@resource.short_id}"
			elsif params[:resourceid]
				@results = @resource.structure_items_display
				@parts = @resource.has_parts_display
				#if @resource.level == 1
					@info = @resource.info_display
					@sponsors = @resource.sponsors_display(@info)
					@articles = @resource.articles_display(@info)
					@author_articles = @resource.author_articles_display(@info)

					@questionEditor = @resource.value("http://scta.info/property/questionListEditor")
					@questionEncoder = @resource.value("http://scta.info/property/questionListEncoder")
					render "text/questions/questions_with_about"
				#else
					#render "text/questions/questions"
				#end
			end
		# TODO review which part if any of the conditional below is necessary
		else
			if @config.commentaryid == "scta"
				@resource = Lbp::Resource.find("http://scta.info/resource/scta")
				@results = @resource.parts_display
				@expression_results = @resource.expressions_display
				@info = @resource.info_display
				render "text/questions/workgrouplist"
			else
				commentaryid = @config.commentaryid
				@resource = Lbp::Resource.find("http://scta.info/resource/#{commentaryid}")
				@results = @resource.structure_items_display
			end
		end
	end

	def info
		# para variable here is simpy the expressionObj
    expression = get_expression(params)
    number = expression.order_number
		manifestations = order_manifestations(expression)
		#TODO: getting author label here requires second query. This not ideal
		author_title = expression.block_author[0][:author_title].to_s
		expression_hash = {
        #:pid => pid,
        :itemid => params[:itemid],
				:long_title => expression.value("http://scta.info/property/longTitle").to_s,
				:author => author_title,
				:expression_url => expression.url,
        :next => if expression.next != nil then expression.next.to_s.split("/").last else nil end,
        :previous => if expression.previous != nil then expression.previous.to_s.split("/").last else nil end,
        :number => number,
				:inbox => if expression.inbox.to_s != nil then expression.inbox.to_s else nil end,
				:is_structure_block => if expression.structure_type.short_id == "structureBlock" then true else false end,
        :manifestations => expression.manifestations.map {|m| m.to_s},
				:manifestations_structure => manifestations,
				:translations => expression.translations.map {|m| m.to_s},
        :abbreviates => expression.abbreviates.map {|item| item.to_s},
        :abbreviatedBy => expression.abbreviatedBy.map {|item| item.to_s},
        :references => expression.references.map {|item| item.to_s},
        :referencedBy => expression.referencedBy.map {|item| item.to_s},
        :copies => expression.copies.map {|item| item.to_s},
        :copiedBy => expression.copiedBy.map {|item| item.to_s},
        :quotes => expression.quotes.map {|item| item.to_s},
        :quotedBy => expression.quotedBy.map {|item| item.to_s},
        :mentions => expression.mentions.map {|item| item.to_s},
				:isRelatedTo => expression.isRelatedTo.map {|item| item.to_s}
				#:wordcount => paratranscript.word_count,
        #:wordfrequency => paratranscript.word_frequency

      }

    render :json => expression_hash

	end

	def status
		url = "http://scta.info/resource/#{params[:itemid]}"
		resource = Lbp::Resource.find(url)
		@title = resource.title
		@manifestations = order_manifestations(resource)
		if @manifestations.count == 0
			flash.clear
		end
		render :status2
	end

	def show
		if params.has_key?(:search)
			flash.now[:notice] = "Search results for instances of #{params[:searchid]} (#{params[:search]}) are highlighted in yellow below."
		end

		# get expression and related info
		@expression = get_expression(params)

		@expression_structure = @expression.structure_type.short_id
		# perform checks
		check_transcript_existence(@expression)
		check_permission(@expression); return if performed?

		if @expression.status == "In Progress" || @expression.status == "draft"
			flash.now[:alert] = "Please remember: the status of this text is draft. You have been granted access through the generosity of the editor. Please use the comments to help make suggestions or corrections."
		end

		#get values  needed for view
		#@expressionid = params[:itemid]
		@title = @expression.title
		@next_expressionid = if @expression.next != nil then @expression.next.to_s.split("/").last else nil end
		@previous_expressionid = if @expression.previous != nil then @expression.previous.to_s.split("/").last else nil end

		#get transcription Object from params
		transcript = get_transcript(params)


		# ms_slugs is not great because its hard coding "critical"
    # what if the name of the manifestion for a critical manifestion was not called critical
    # more idea to check database to get a manifestationType
    # but this could be costly. If there were 20 or 30 manifestations
    # then you'd be making lots of requests to db
    # this map is reused in the paragraph controller as well; should be refactored
    ms_slugs = @expression.manifestations.map {|m| unless m.to_s.include? 'critical' then m.to_s.split("/").last end}.compact
		default_wit_param = ms_slugs[0]


		#prepare xslt arrays to be used for transformation
			#always remember single quotes for paramater value
			#specify if global image setting is true or false


		xslt_param_array = ["default-ms-image", if default_wit(params, @expression) == "critical" then "'#{default_wit_param}'" else "'#{default_wit(params, @expression)}'" end,
				"default-msslug", "'#{default_wit(params, @expression)}'",
				"show-images", "'#{@config.images.to_s}'",
				"by_phrase", "'#{t(:by)}'",
				"edited_by_phrase", "'#{t(:edited_by)}'"]

		#using "file" path, there is no longer any need to check the structure type; Exist will simply construct a new document
		#for the expression at any level in the hierarchy
		if params[:path] == "file"
			file = transcript.file(confighash: @config.confighash, path: params[:path])
			xslt_param_array += ["file-path", "'#{file.file_path.to_s}'"]
			@transform = file.transform_main_view(xslt_param_array)
		else
			if @expression_structure == "structureItem"
				file = params[:branch] ? transcript.file(branch: params[:branch], confighash: @config.confighash, path: "doc") : transcript.file(confighash: @config.confighash, path: "doc")
				xslt_param_array += ["file-path", "'#{file.file_path.to_s}'"]
				@transform = file.transform_main_view(xslt_param_array)
			elsif @expression_structure == "structureBlock"
				#path = params[:path] ? params[:path] : "doc"
				file = transcript.file_part(confighash: @config.confighash, partid: params[:itemid], path: "doc")
				xslt_param_array += ["file-path", "'#{file.file_path.to_s}'"]
				@transform = file.transform_plain_text(xslt_param_array)
			end
		end

		#version information
		## TODO: refactor; takes 4 requests which seems like too many
		@current_order_number = transcript.value("http://scta.info/property/versionOrderNumber")
		@current_version_label = transcript.value("http://scta.info/property/versionLabel")
		@current_review_state = transcript.value("http://scta.info/property/hasReview")
		@version_history = MiscQuery.new.version_history_info(transcript.to_s)

	end

	def xml
		expression = get_expression(params)
		@expression_structure = expression.structure_type.short_id

		check_permission(expression)

		transcript = get_transcript(params)

		if @expression_structure == "structureItem"
			file = transcript.file(confighash: @config.confighash)
			@nokogiri = file.nokogiri
		elsif @expression_structure == "structureBlock"
			# NOTE: don't be confused by item id here; it is the id of the block express

app/helpers/text_helper.rb
module TextHelper
end

app/views/text/_text_nav_bar.html.erb
<nav id="lbp-text-tool-bar" class="navbar navbar-default navbar-fixed-bottom" style="background-color: <%= @config.light_color %>;">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#lbp-text-tool-bar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/"><%= t(:text_tool_bar) %></a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div id="lbp-text-tool-bar-collapse" class="collapse navbar-collapse" >
      <ul class="nav navbar-nav">
        <% if @expression.level == 1 %>
        <li><%= link_to "Text Home", "/#{@expression.short_id}" %></li>
        <% else %>
        <li><%= link_to "Text Home", "/#{@expression.top_level_expression.short_id}" %></li>
        <% end %>
        <% unless (params.has_key?(:msslug) && params[:msslug] != "critical") || @expression_structure == "structureBlock" %>
          <li><a class="js-show-outline" data-itemid="<%= params[:itemid] %>"><%= t(:text_outline) %></a></li>
        <% end %>
        <% if @previous_expressionid != nil  %>
          <li><%= link_to t(:previous), show_text_path(@previous_expressionid, params[:msslug]),  data: { keybinding: 'p' } %></li>
        <% end %>
        <% if @next_expressionid != nil %>
          <li><%= link_to t(:next), show_text_path(@next_expressionid, params[:msslug]), data: { keybinding: 'n' } %></li>
        <% end %>
          <li><a href="/text/status/<%= params[:itemid] %>"><%= t(:available_transcriptions) %></a></li>




      </ul>

      <ul class="nav navbar-nav navbar-right">
      <!-- first condition is needed to avoid error in second condition in the current_user.admin? call -->
      <% if current_user %>
        <% if current_user.admin? || check_editor_access(current_user, @expression.short_id, @expression.top_level_expression.short_id) %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Editor Tools <span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <li><%= link_to "Review Comments for this Text", list_comments_path(params[:itemid]) %></li>
              <li><%= link_to "Review All Comments", comments_path %></li>
              <li><%= link_to "View Analytics" %></li>
            </ul>
          </li>
          <% end %>
        <% end %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><%= t(:text_tools) %> <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="#" class="js-show-item-xml" data-itemid="<%= params[:itemid] %>" data-manifestation-id="<%= params[:msslug] %>" data-transcript-id="<%= params[:transcriptslug] %>">XML</a></li>
            <li class="divider"></li>
            <li><a href="#" class="js-show-paragraph-info" data-itemid="<%= params[:itemid] %>" data-pid="<%= params[:itemid] %>">Text Info/Stats</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/text/archive.html.erb
<%= raw(@text) %>>

app/views/text/draft_permissions.html.erb
<div id="draftview" class="container">
		<h3>This text is currently a private draft</h3>
		<p>Depending on the state of a transcriptions, editors will often designate their text as a "draft". This means that, while an edition or transcription, has been started it is not yet ready to be viewed by the public. Often an editor will allow and interested reader access to the text, with the understanding that the text is a work in progress.</p>
		<% if !user_signed_in? %>
			<p>To view this text you will need to first create a user account. Then you can return and request permission.</p>
		<% else %>
			<h3> To request draft permissions for this text, please tell the editor a little about yourself and your interest in this text. </h3>
			<%= form_for(:access_request, url: access_requests_path, method: :post) do |f| %>
	 			<div class="field">
	 			<%= f.hidden_field :user_id, :value => current_user.id %>
			  <%= f.hidden_field :itemid, value: params[:itemid] %>
			  <%= f.hidden_field :commentaryid, value: @config.commentaryid %>
			  </div>
			  <div class="field">
			    <%= f.text_area :note, :class => 'ckeditor' %>
			  </div>
			  <div class="actions">
			    <%= f.submit %>
			  </div>
			<% end %>
		<% end %>
</div>

app/views/text/index.html.erb
<div class="container">
  <h1><%= t(:toc) %></h1>

  <div id="lbp-toc-container" class="container">
    <div class="row">
      <div class="col-xs-3 col-md-4">
        <h3>Items</h3>
          <div id="lbp-toc-sidebar">
            <ul class="list-group">
      	      <% @results.each do |result| %>
        	      <% link = "text/" + result[:item].to_s.split('/').last %>
        	      <li class="list-group-item">
        	      	<span class="lbp-item-name"><% if result[:status] != "Not Started" %>
        	      		<%=  link_to result[:title], link %></span></br>
                    <span class="small"><%= link_to "Outline", "#", :class => "js-show-toc", "data-itemid" => result[:item].to_s.split("/").last %></span>
                    
        	      	<% else %>
        	      		<%= result[:title] %>
        					<% end %>
        				</li> 
  	         <% end %>
      	   </ul>
         </div>
      </div>
      <div id="lbp-toc-mainwindow">
        <h3>Outline</h3>
        <div id="lbp-toc-window" class="col-xs-9 col-md-8">
        </div>
      </div>
    </div>
  </div>
</div>

app/views/text/info.html.erb
<div id="lbp-info-container" class="container">
	<h1>Text Info/Stats for <%= @title %></h1>
	<div class="row">
		<div class="col-md-3">
			<div class="panel panel-default">
			  <div class="panel-heading">
			  	<h3 class="panel-title">Mentions</h3>
			  </div>
			  <div class="panel-body">
			    <table class="table table-striped table-hover">
			    	<% @name_results.each do |result| %>
			    	<tr>
			    		<td><%= link_to result[:nameTitle].to_s, result[:name].to_s, target: "_blank" %></td>
			    		
			    	</tr>
			    	<% end %>
			    </table>
			  </div>
			</div>
		</div>
		<div class="col-md-3">
			<div class="panel panel-default">
				<div class="panel-heading">
				  	<h3 class="panel-title">Quotations Used</h3>
				  </div>
				  <div class="panel-body">
				    <table class="table table-striped table-hover">
				    	<% @quote_results.each do |result| %>
				    	<tr>
				    		<td><%= result[:quoteText].to_s %></td>
				    		<td><%= link_to result[:quoteCitation].to_s, result[:quote].to_s, target: "_blank" %></td>

				    	</tr>
				    	<% end %>
				    </table>
				  </div>
				</div>
			</div>
		</div>
	</div>
</div>

	

		

app/views/text/show.html.erb
<!-- style override for body to prevent overlap with bottom tool bar -->
<style type="text/css">
body {padding-bottom: 50px;}
</style>
<!-- end of style override -->

<% if @version_history.count > 0 %>
<div id="version-wrapper" class="alert alert-warning alert-dismissible" role="alert">
  <p id="version-wrapper-title">This Article Has Multiple Indexed Versions</p>
  <div id="version-list">
    <% @version_history.each do |result| %>
		<% if @current_order_number.to_s.to_i == result[:order_number].to_s.to_i + 1%>
    <p><%= @current_version_label %>
			<%= @current_review_state ? " (Peer Reviewed)" : nil %>
      (Currently Viewing)
		</p>
    <% end %>
    <p><a href="/text/<%= result[:version_shortId] %>"><%= result[:version_label] %></a> <%= result[:review] ? "(Peer Reviewed)" : nil %></p>
    <% if @current_order_number.to_s.to_i == result[:order_number].to_s.to_i - 1%>
    <p><%= @current_version_label %>
		<%= @current_review_state ? " (Peer Reviewed) " : nil %>
    (Currently Viewing)
    </p>
    <% end %>
  </div>
<% end %>
</div>
<% end %>

<%= render "text_nav_bar" %>

<% if params[:search] != nil %>
	<div id="lbp-text-body" class="container" data-search="<%= params[:search] %>" data-searchid="<%= params[:searchid] %>">
<% else %>
	<div id="lbp-text-body" class="container">
<% end %>
	<%= raw(@transform) %>
</div>
<!-- side window -->
<div id="lbp-side-window" style="background-color: <%= @config.light_color %>;">
	<nav id="lbp-bottom-window-nav-bar">
		<div class="container-fluid">
			<ul class="nav navbar-nav">
				<li><a class="js-close-side-window">Close</span></a></li>
				<li id="lbp-min-side-window"><a class="js-minimize-side-window">Min</span></a></li>
				<li id="lbp-max-side-window"><a class="js-maximize-side-window">Max</span></a></li>
			</ul>
		</div>
	</nav>
	<div id="lbp-side-window-container" style="">
	</div>
</div>
<!-- bottom window -->
<div id="lbp-bottom-window" style="background-color: <%= @config.dark_color %>;">
	<nav id="lbp-bottom-window-nav-bar">
		<div class="container-fluid">
			<div class="navbar-header">
	      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#lbp-bottom-window-navbar-collapse">
	        <span class="sr-only">Toggle navigation</span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	      </button>
	    </div>
			<div class="collapse navbar-collapse" id="lbp-bottom-window-navbar-collapse">
	    	<ul class="nav navbar-nav">
					<li>
						<a class="js-expand-para-comment">Max
							<span class="dropup">
								<span class="caret"></span>
							</span>
						</a>
					</li>
					<li><a class="js-halfsize-para-comment">50%</a></li>
					<li><a class="js-minimize-para-comment">Min<span class="caret"></span></a></li>
					<li><a class="js-close-para-comment">Close</span></a></li>
          <li><a href="#" class="js-toggle-scroll-lock">Lock Scroll</span></a></li>
					<li><a class="js-toggle-sync">Sync Panels</span></a></li>
				</ul>
			</div>
		</div>
	</nav>
	<div id="lbp-bottom-window-container" class="container">
	</div>
</div>

app/views/text/status.html.erb
<div id="lbp-item-status-container" class="container">
  <% unless @results.count ==  0 %>
    <h3>Available transcriptions for: <%= @results.first[:item_title] %></h3>
    <table class="table table-striped table-hover">

      <% @results.each do |result|
        slug = result[:manifestation].to_s.split("/").last
        type = result[:transcript_type]
        status = result[:transcript_status]
        if type == "critical" || type == "Critical"
          link = "/text/#{@itemid}"
        else
          link = "/text/#{@itemid}/#{slug}"
        end
        %>
          <tr>
            <td><%= link_to result[:transcript_title].to_s, link %></td>
            <td><%= "type: #{type}" %></td>
            <td><%= "status: #{status}" %></td>
            <td><a href="/text/pdf?id=<%= result[:manifestation] %>">PDF</td>
          </tr>
      <% end %>
    </table>
    <% unless @translation_results.count ==  0 %>
      <h3>Available Translations for: <%= @results.first[:item_title] %></h3>
      <table class="table table-striped table-hover">

        <% @translation_results.each do |result|
          slug = result[:manifestation].to_s.split("/").last
          language = result[:language]
          status = result[:transcript_status]
          link = "/text/#{@itemid}/#{slug}"
        %>
            <tr>
              <td><%= link_to result[:transcript_title].to_s, link %></td>
              <td><%= "language: #{language}" %></td>
              <td><%= "status: #{status}" %></td>
            </tr>
        <% end %>
      </table>
      <% end %>
  <% else %>
    <div style="text-align: center; height: 400px; margin-top: 100px">
      <h4>Sorry this text has not been started. <%= link_to "Return to Table of Contents", table_of_questions_path %></h4>
    </div>
  <% end %>
</div>

app/views/text/status2.html.erb
<div id="lbp-item-status-container" class="container">
  <% unless @manifestations.count ==  0 %>
    <h3>Available transcriptions for <%= @title %></h3>
    <% @manifestations.each do |result| %>
      <p><%= result[:manifestation_title] %></p>
      <table class="table table-striped table-hover">
      <% result[:transcriptions].each do |transcript| %>
        <tr>
          <td><a href="<%= transcript[:transcript_link] %>"><%=  transcript[:transcript_title] %></a></td>
          <td><%= "type: #{transcript[:transcript_type]}" %></td>
          <td><%= "status: #{transcript[:transcript_status]}" %></td>
          <td><a href="/text/pdf?id=<%= transcript[:transcript] %>">PDF</td>
        </tr>
      <% end %>
      </table>
    <% end %>
  <% else %>
    <div style="text-align: center; height: 400px; margin-top: 100px">
      <h4>Sorry this text has not been started. <%= link_to "Return to Table of Contents", table_of_questions_path %></h4>
    </div>
  <% end %>
</div>

app/views/text/toc.html.erb
<div id="lbp-toc-container">
<%= raw(@toc) %>
</div>

app/views/text/xml.html.erb
<div id="lbp-xml-container">
<script type="text/javascript">
$(document).ready(function(){
	$("pre.xmlCode").snippet("xml", {style: "acid"});
});
</script>
<!-- cant figure out why this won't work through asset pipeline -->

<pre id="lbp-xml" class="xmlCode"><%= @nokogiri %></pre>
</div>