config/routes.rb
Rails.application.routes.draw do

  get 'errors/not_found'
  get 'errors/internal_server_error'

  resources :access_requests

  root 'pages#home'

  devise_for :users, controllers: { sessions: "users/sessions", profiles: "users/profiles", registrations: "users/registrations"}

  get 'posts/list' => 'posts#list'
  resources :posts

  resources :comments, except: [:new]

  resources :settings

  match "/404", to: "errors#not_found", via: :all
  match "/500", to: "errors#internal_server_error", via: :all

  get 'articles/:articleid(/:transcriptionid)' => 'articles#show', as: :show_article
  get 'articles' => 'articles#index', as: :articles

  get 'biography' => 'pages#biography'
  get 'bibliography' => 'pages#bibliography'

  get "comments/new/:itemid(/:pid)" => 'comments#new', as: :new_comment
  get "comments/list/:itemid(/:pid)" => 'comments#list', as: :list_comments

  get "index/(:expressionid)" => 'indices/indices#index'

  get "index/:expressionid/names/list(/:category)" => 'indices/names#list'
  get "index/:expressionid/names/show(/:nameid)" => 'indices/names#show'
  get "index/:expressionid/names/categories" => 'indices/names#categories'

  get "index/:expressionid/titles/list(/:category)" => 'indices/titles#list'
  get "index/:expressionid/titles/show(/:titleid)" => 'indices/titles#show'
  get "index/:expressionid/titles/categories" => 'indices/titles#categories'

  get "index/:expressionid/quotes/list(/:category)" => 'indices/quotes#list'
  get "index/:expressionid/quotes/show(/:quoteid)" => 'indices/quotes#show'
  get "index/:expressionid/quotes/categories" => 'indices/quotes#categories'

scope 'codices' do
  get 'list' => 'codices#list'
  get '(/:shortid)' => 'codices#show'
end
scope 'paragraphs' do
  get 'index' => 'paragraphs#index'
  get 'info' => 'paragraphs#info'
  get 'plaintext' => 'paragraphs#plaintext'
  get 'show2' => 'paragraphs#show2'

  get 'collation/:itemid' => 'paragraphs#collation', as: :paragraphs_collation
  get 'xml/:itemid/:pid(/:msslug)' => 'paragraphs#xml', as: :paragraphs_xml
  get 'json/:itemid/(/:msslug)(/:transcriptslug)' => 'paragraphs#json', as: :paragraphs_json
  get 'variants/:itemid/(/:msslug)(/:transcriptslug)' => 'paragraphs#variants', as: :paragraphs_variants
  get 'notes/:itemid/(/:msslug)(/:transcriptslug)' => 'paragraphs#notes', as: :paragraphs_notes

  get ':itemid/:pid(/:msslug)' => 'paragraphs#show'
end

  get 'permissions' => 'pages#permissions'

  get 'search' => 'search#show', as: :show_search
  get 'search/questions' => 'search#questions', as: :search_questions
  get 'search/index' => 'search#index', as: :show_search_index
scope "text" do
  get '' => 'text#index'
  get 'draft_permissions/:itemid' => 'text#draft_permissions'
  get 'questions(/:resourceid)' => 'text#questions', as: :table_of_questions
  get 'info/:itemid' => 'text#info', :constraints => { :itemid => /[0-9A-Za-z\-\.]+/ }
  get 'status/:itemid' => 'text#status'
  get 'toc/:itemid(/:msslug)' => 'text#toc'
  get 'plaintext/:itemid(/:msslug)(/:transcriptslug)' =>'text#plain_text', as: :plain_text
  get 'clean/:itemid(/:msslug)(/:transcriptslug)' =>'text#clean', as: :clean
  get 'xml/:itemid(/:msslug)(/:transcriptslug)' => 'text#xml'
  get 'pdf' => 'text#pdf'
  get 'archive' => 'text#archive'
  get ':itemid(/:msslug)(/:transcriptslug)' => 'text#show', as: :show_text
end

  get 'paragraphimage/showfoliozoom' => 'paragraphimage#showfoliozoom'
  get 'paragraphimage/showzoom/:itemid/:msslug' => 'paragraphimage#showzoom'

  get 'users/profiles/:id' => 'users/profiles#show', as: :users_profile
  delete 'users/profiles/:id' => 'users/profiles#destroy', as: :destroy_users_profile
  put 'users/profiles/:id' => 'users/profiles#update', as: :update_users_profile
  post 'users/profiles' => 'users/profiles#create', as: :create_users_profile
  get 'users/profiles' => 'users/profiles#index'

  get 'accesspoints' => 'access_points#index', as: :access_points
  get 'accesspoints/:commentaryid/:itemid/:role' => 'access_points#show', as: :access_point
  post 'accesspoints/:id' => 'access_points#create', as: :create_access_point
  delete 'accesspoints/:id' => 'access_points#destroy', as: :delete_access_point

  match "/:resourceid", to: "text#questions", via: :all

end

app/models/user.rb
class User < ActiveRecord::Base
  
  enum role: [:admin, :user]
  enum language: { en: 'en', de: 'de', fr: 'fr', la: 'la'}
	has_many :comments, dependent: :destroy
	has_many :posts, dependent: :destroy
  has_many :access_requests, dependent: :destroy
	has_and_belongs_to_many :access_points

  after_initialize :set_default_role, :if => :new_record?
  
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def set_default_role
  	self.role ||= :user
  end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when omniauth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/profiles_controller.rb
class Users::ProfilesController < ApplicationController
	before_filter :authenticate_user!
  

	def index
		#unless current_user.admin?
		 #	redirect_to "/permissions", :alert => "Access denied."
    #end
    @users = User.all
    @sorted_users = @users.sort_by {|row| row[:email]}
    @profile = User.new
    authorize @profile

	end
	def show
		@user = User.find(params[:id])
    @comments = Comment.where(user_id: @user.id)
    @general_comments = @comments.select {|comment| comment.access_type == 'general'}
    @personal_comments = @comments.select {|comment| comment.access_type == 'personal'}
    @editorial_comments = @comments.select {|comment| comment.access_type == 'editorial'}
		
    @profile = @user
		#note that user in the authorize method is actually the second arg
		#corresponding to the @profile arg in the pundit policy
		authorize @profile
  end
  def create
  	@profile = User.new(profile_params)
    authorize @profile 
    if @profile.save
      redirect_to users_profiles_path, :notice => "Profile successfully added"
    end
  end
  def update

  	@profile = User.find(params[:id])
    authorize @profile
    if @profile.update(profile_params)
			redirect_to users_profile_path(@profile), :notice => "Profile successfully update"
		end
  end
  def destroy 

  	@profile = User.find(params[:id])
    authorize @profile
    if @profile.destroy
			redirect_to users_profiles_path, :notice => "Profile successfully deleted"
		end
  end
  

  private 
	  def profile_params
	    params.require(:profile).permit(:email, :password, :role)
	  end

end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
# before_filter :configure_sign_up_params, only: [:create]
 before_filter :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  #GET /resource/edit
  #def edit
  #   super
  #end

  #PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # You can put the params you want to permit in the empty array.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.for(:sign_up) << :attribute
  # end

  # You can put the params you want to permit in the empty array.
   def configure_account_update_params
     devise_parameter_sanitizer.for(:account_update) << [:language]
   end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_filter :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # You can put the params you want to permit in the empty array.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/views/users/profiles/index.html.erb
<% if current_user.admin? %>
<div class="container">
	<h1>Users</h1>
	<table class="table table-striped table-hover">
		<thead>
			<tr>
				<td>Email</td>
				<td>Role</td>
				<td>Preferred Language</td>
				<td>Created at</td>
			</tr>
		</thead>
		<tbody>
			<% @sorted_users.each do |user| %>
				<tr>
					<td><%= link_to user.email, users_profile_path(user) %></td>
					<td><%= user.role %></td>
					<td><%= user.language %></td>
					<td><%= user.created_at %></td>
					<td><%= link_to "Destroy", destroy_users_profile_path(user), method: :delete %></td>
				</tr>
			<% end %>
		</tbody>
	</table>
</div>
<div class="container">
	<p>As admin, you can create a new user </p>
	<%= form_for(:profile, url: :create_users_profile) do |f| %>
	  <div class="field">
	    <%= f.label :email %><br />
	    <%= f.email_field :email, autofocus: true %>
	  </div>
		<div class="field">
	    <%= f.label :password %>
	    <br />
	    <%= f.password_field :password, autocomplete: "off" %>
	  </div>
	  <div class="role">
	    <%= f.label :role %>
	    <br />
	    <%= f.text_field :role, autocomplete: "off" %>
	  </div>
	  
		<div class="actions">
			<br />
	    <%= f.submit "Create User" %>
	  </div>
	<% end %>
</div>
<% else %>
<p>You are not authorized to view the profiles list</p>
<% end %>

		

app/views/users/profiles/show.html.erb
<div class="container center">
	<h1>User Profile</h1>
	<hr/>
	<div>
		<h2>User info</h2>
		<p><%= @user.email %></p>
		<p><%= @user.role %></p>
		<p><%= @user.created_at %></p>
		<p>Preferred Language <%= @user.language %></p>
		<p><%= link_to t(:edit_profile), '/users/edit' %></p>
	</div>
	<hr/>
	<div>
	<% unless @comments.empty? %>
	<h2>My Comments</h2>
	<% end %>
	<br/>
	<% unless @personal_comments.empty? %>
		<h3 class="small" style="font-weight: bold">My Private Notes</h4>
		<table class="table table-striped table-hover">
		<thead style="font-weight: bold">
			<td>Created at:</td>
					<td>User</td>
					<td>pid</td>
					<td>itemid</td>
					<td>commentaryid</td>
					<td style="width: 50%">comment</td>
			</thead>
			<tbody>
			<% @personal_comments.each do |comment| %>
				<tr>
					<td><%= comment.created_at %></td>
					<td><p><%= comment.user.email %></p></td>
					<td><%= link_to comment.pid, "http://#{comment.commentaryid}.lombardpress.org/text/#{comment.itemid}##{comment.pid}" %></td>
					<td><%= link_to comment.itemid, "http://#{comment.commentaryid}.lombardpress.org/text/#{comment.itemid}" %></td>
					<td><%= link_to comment.commentaryid, "http://#{comment.commentaryid}.lombardpress.org" %></td>
					<td style="width: 50%"><%= raw(comment.comment) %></td>
					<td>
					<%= form_for(:comment, url: comment_path(comment), method: :delete) do |f| %>
								<%= f.hidden_field :itemid, value: params[:itemid] %>
								<%= f.hidden_field :redirect_target, value: "profile" %>
								<%= f.submit "Delete" %>
							<% end %>
					</td>
				</tr>
			<% end %>
			</tbody>
		</table>
	<% end %>
	<% unless @general_comments.empty? %>
		<h3 class="small" style="font-weight: bold">My Public Comments</h4>
		<table class="table table-striped table-hover">
		<thead style="font-weight: bold">
			<td>Created at:</td>
					<td>User</td>
					<td>pid</td>
					<td>itemid</td>
					<td>commentaryid</td>
					<td style="width: 50%">Comment</td>
			</thead>
			<tbody>
			<% @general_comments.each do |comment| %>
				<tr>
					<td><%= comment.created_at %></td>
					<td><p><%= comment.user.email %></p></td>
					<td><%= link_to comment.pid, "http://#{comment.commentaryid}.lombardpress.org/text/#{comment.itemid}##{comment.pid}" %></td>
					<td><%= link_to comment.itemid, "http://#{comment.commentaryid}.lombardpress.org/text/#{comment.itemid}" %></td>
					<td><%= link_to comment.commentaryid, "http://#{comment.commentaryid}.lombardpress.org" %></td>
					<td style="width: 50%"><%= raw(comment.comment) %></td>
					<td>
					<%= form_for(:comment, url: comment_path(comment), method: :delete) do |f| %>
								<%= f.hidden_field :itemid, value: params[:itemid] %>
								<%= f.hidden_field :redirect_target, value: "profile" %>
								<%= f.submit "Delete" %>
							<% end %>
					</td>
				</tr>
			<% end %>
			</tbody>
		</table>
	<% end %>
	<% unless @editorial_comments.empty? %>
		<h3 class="small" style="font-weight: bold">My Editorial Comments</h4>
		<table class="table table-striped table-hover">
			<thead style="font-weight: bold">
			<td>Created at:</td>
					<td>User</td>
					<td>pid</td>
					<td>itemid</td>
					<td>commentaryid</td>
					<td style="width: 50%">Comment</td>
			</thead>
			<tbody>
			<% @editorial_comments.each do |comment| %>
				<tr>
					<td><%= comment.created_at %></td>
					<td><p><%= comment.user.email %></p></td>
					<td><%= link_to comment.pid, "http://#{comment.commentaryid}.lombardpress.org/text/#{comment.itemid}##{comment.pid}" %></td>
					<td><%= link_to comment.itemid, "http://#{comment.commentaryid}.lombardpress.org/text/#{comment.itemid}" %></td>
					<td><%= link_to comment.commentaryid, "http://#{comment.commentaryid}.lombardpress.org" %></td>
					<td style="width: 50%"><%= raw(comment.comment) %></td>
					<td>
					<%= form_for(:comment, url: comment_path(comment), method: :delete) do |f| %>
								<%= f.hidden_field :itemid, value: params[:itemid] %>
								<%= f.hidden_field :redirect_target, value: "profile" %>
								<%= f.submit "Delete" %>
							<% end %>
					</td>
				</tr>
			<% end %>
			</tbody>
		</table>
	<% end %>
	</div>
	<hr/>
	<div>
		<% if @user.access_points.count > 0  %>
			<h2>Has individual access to</h2>
			<table class="table table-striped table-hover">
				<% sorted_access_points = @user.access_points.sort_by {|ap| ap[:itemid]} %>
				<% sorted_access_points.each do |access_point| %>
					<tr>
						<td><%= link_to access_point.itemid, "http://#{access_point.commentaryid}.lombardpress.org/text/#{access_point.itemid}" %></td>
						<td><%= access_point.commentaryid %></td>
						<td><%= access_point.role %></td>
						<% if current_user.admin? %>
							<td>
								<%= form_for(:access_point, url: delete_access_point_path, method: :delete) do |f| %>
								<%= f.hidden_field :itemid, value: access_point.itemid %>
								<%= f.hidden_field :commentaryid, value: access_point.commentaryid %>
								<%= f.hidden_field :role, value: access_point.role %>
								<%= f.submit "Remove" %>
							<% end %>
						</td>
					<% end %>
					</tr>
				<% end %>
			</table>
		<% end %>
	</div>
	<hr/>
	<div>
	<% if @user.access_requests.count > 0  %>
		<h2>Has open requests for </h2>
		<table class="table table-striped table-hover">
			<% @user.access_requests.each do |access_request| %>
				<% if access_request.open? %>
					<tr>
						<td><%= access_request.itemid %></td>
						<td><%= access_request.commentaryid %></td>
						<% if current_user.admin? %>
							<td>
								<%= form_for(:access_point, url: create_access_point_path(access_request.user.id), method: :post) do |f| %>
								<%= f.hidden_field :itemid, value: access_request.itemid %>
								<%= f.hidden_field :commentaryid, value: access_request.commentaryid %>
								<%= f.submit "Add Access Point" %>
								<% end %>
							</td>
						<% end %>
					</tr>
				<% end %>
			<% end %>
		</table>
	<% end %>
	</div>
	<hr/>
	<% if current_user.admin? %>
		<div style="border-top: 1px solid black">
			<h2>Admin Options</h2>
			
			<div style="margin: 10px; border-top: 1px dotted gray;">
				<%= form_for(:access_point, url: create_access_point_path, method: :post) do |f| %>
					<p>Add Access Point</p>
					<%= f.text_field :itemid %>
					<%= f.text_field :commentaryid %>
					<%= f.select(:role) do %> 
		      	<% AccessPoint.roles.each do |role, int| %>
		      		<%= content_tag(:option, role, value: role) %>
		    		<% end %>
		  		<% end %>
					<%= f.submit "Add Access Point" %>
				<% end %>
			</div>
			<div style="margin: 10px; border-top: 1px dotted gray;">
				<%= form_for(:profile, url: :update_users_profile, method: :put) do |f| %>
				<p>Change User Role</p>
				  <%= f.text_field :role, autocomplete: "off" %>
				  <%= f.submit "Update User" %>
				<% end %>
				<br /><br />
				  <%= link_to "Back to Profiles List", users_profiles_path %>
			</div>
		</div>
	<% end %>
</div>
		